[package]
name = "get_up"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
octocrab = "0.15"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.52"
